device: cuda
wandb_enabled: False
dataset:
  file: ../../input/brca_small.csv
  patches_dir: ../../input/patches/
  signatures: ../../input/signatures.csv
model:
  name: TBD
training:
  train_size: 0.5
  loss: ces
  epochs: 20
  lr: 0.0002
  weight_decay: 0.00001
  grad_acc_step: 32