device: cuda
wandb_enabled: True
dataset:
  name: TCGA-GBMLGG
  file: /work/h2020deciderficarra_shared/mgualtieri/gbmlgg/gbmlgg.csv
  patches_dir: /work/h2020deciderficarra_shared/mgualtieri/gbmlgg/slides/
  signatures: /work/tesi_mgualtieri/decider/multimodal-path-omic/input/signatures/signatures.csv
  decider_only: False
  normalize: False
  standardize: False
model:
  name: NaCAGAT
  load_from_checkpoint: ~ # checkpoints/MCAT_20_202408081300.pt
  checkpoint_epoch: 0  # 0 if saving is not necessary
  checkpoint_dir: checkpoints/
  fusion: concat # concat, gated_concat, bilinear
  model_size: medium
training:
  train_size: 0.8
  loss: ces # ces, sct
  epochs: 20
  optimizer: adam # sgd, adam, rms, adamax
  lr: 0.000002 # 0.0002
  weight_decay: 0.0001 # 0.00001
  grad_acc_step: 32
  scheduler: ~ # ~, exp
  alpha: 0.25
  lambda: 0.0
  gamma: 1.0
inference:
  attention_file: attention_outputs/ATTN_TCGA-A2-A0EY-01Z-00-DX1.2F2428B3-0767-48E0-AC22-443C244CBD16.pt
  dataset:
    file: ../../input/inference/brca.csv
    patches_dir: ../../input/inference/
    signatures: ../../input/signatures.csv
  model:
    name: NaCAGAT
    load_from_checkpoint: checkpoints/NaCAGAT_20_202408161615.pt