device: cuda
wandb:
  enabled: True
  project: CCNE1
dataset:
  name: DECIDER-OV
  file: /work/h2020deciderficarra_shared/mgualtieri/ov/decider_ov.csv
  patches_dir: /work/h2020deciderficarra_shared/mgualtieri/ov/slides/
  signatures: /work/tesi_mgualtieri/decider/multimodal-path-omic/input/signatures/ccne1.csv
  decider_only: True
  normalize: False
  standardize: False
model:
  name: NaCAGaT
  load_from_checkpoint: ~ # checkpoints/MCAT_20_202408081300.pt
  checkpoint_epoch: 20  # 0 if saving is not necessary
  checkpoint_dir: checkpoints/
  fusion: concat # concat, gated_concat, bilinear
  model_size: small
training:
  leave_one_out: D329
  output_attn_epoch: 5
  test_output_dir: outputs/
  train_size: 0.8
  loss: ces # ces, sct
  epochs: 20
  optimizer: adam # sgd, adam, rms, adamax
  lr: 0.0002 # 0.0002
  weight_decay: 0.00001 # 0.00001
  grad_acc_step: 32
  scheduler: ~ # ~, exp
  alpha: 0.75
  lambda: 0.0
  gamma: 1.0
