device: cpu
wandb_enabled: False
dataset:
  name: TCGA-GBMLGG
  file: ../../input/gbmlgg/gbmlgg.csv
  patches_dir: ../../input/gbmlgg/patches/
  signatures: ../../input/signatures.csv
  normalize: False
  standardize: False
  decider_only: False
model:
  name: NaCAGAT
  load_from_checkpoint: ~ # checkpoints/MCAT_20_202408081300.pt
  checkpoint_epoch: 0  # 0 if saving is not necessary
  checkpoint_dir: checkpoints/
  fusion: concat # concat, gated_concat, bilinear
  model_size: medium
training:
  train_size: 0.8
  loss: ces # ces, sct
  epochs: 2
  optimizer: adam # adam, rms, adamax
  lr: 0.0002 # 0.0002
  weight_decay: 0.00001 # 0.00001
  grad_acc_step: 32
  scheduler: ~ # ~, exp
  alpha: 0.75
  lambda: 0.0000001
  gamma: 0.95
