device: cuda
dataset:
  name: DECIDER-OV
  file: /work/h2020deciderficarra_shared/mgualtieri/ov/decider_ov.csv
  patches_dir: /work/h2020deciderficarra_shared/mgualtieri/ov/slides/
  signatures: /work/tesi_mgualtieri/decider/multimodal-path-omic/input/signatures/ccne1.csv
  decider_only: True
  normalize: False
  standardize: False
model:
  name: NaCAGaT
  checkpoint: /work/tesi_mgualtieri/decider/multimodal-path-omic/models/nacagat/checkpoints/NaCAGaT_DECIDER-OV_E20_202410180948.pt
  fusion: concat # concat, gated_concat, bilinear
  model_size: medium
inference:
  patient: D335
  output_dir: outputs/
