device: cuda
wandb_enabled: True
dataset:
  dataset_file: ../../input/dataset.hdf5
model:
  name: TSMCAT
training:
  train_size: 0.8
  loss: ces
  epochs: 20
  lr: 0.0002
  weight_decay: 0.00001
  grad_acc_step: 32
  seq_reducer: none # none, attention, pooling, conv, perceiver
  reduced_size: 10