device: cuda
wandb_enabled: True
dataset:
  dataset_file: ../../input/genomic.hdf5
model:
  name: SNN
training:
  train_size: 0.8
  loss: nlls # ces, nlls, coxs
  model_size: small # large
  epochs: 20
  batch_size: 128
  lr: 0.0001
  weight_decay: 0.00001
  grad_acc_step: 1