device: cuda
wandb_enabled: True
dataset:
  name: TCGA-BRCA
  file: /work/h2020deciderficarra_shared/mgualtieri/brca/brca.csv
  patches_dir: /work/h2020deciderficarra_shared/mgualtieri/brca/slides/
  signatures: /work/tesi_mgualtieri/decider/multimodal-path-omic/input/signatures/signatures.csv
model:
  name: MCAT
  load_from_checkpoint: ~ # checkpoints/MCAT_20_202408081300.pt
  checkpoint_epoch: 20 # 0 if saving is not necessary
  checkpoint_dir: checkpoints/
  fusion: gated_concat # concat, gated_concat, bilinear
  model_size: medium
training:
  train_size: 0.8
  loss: sct # ces
  epochs: 20
  lr: 0.0001
  weight_decay: 0.00001
  grad_acc_step: 32
inference:
  attention_file: attention_outputs/attention.pt
  dataset:
    file: ../../input/inference/brca.csv
    patches_dir: ../../input/inference/
    signatures: ../../input/signatures.csv
  model:
    name: MCAT
    load_from_checkpoint: checkpoints/MCAT_20_202408161615.pt
