device: cuda
wandb_enabled: False
dataset:
  file: ../../input/brca_small.csv
  patches_dir: ../../input/patches/
  signatures: ../../input/signatures.csv
model:
  name: MCAT
  use_checkpoint: checkpoints/MCAT_20_202408081300.pt
  checkpoint_epoch: 10 # 0 if saving is not necessary
  checkpoint_dir: checkpoints/
training:
  train_size: 0.5
  loss: ces
  epochs: 20
  lr: 0.0002
  weight_decay: 0.00001
  grad_acc_step: 32